### ISSUE TITLE
Fails to convert certain resources in a large server

### ISSUE THREAD

**Issue by ivoryyy** [Holfz/noah_fxmanifest_converter#1]
Using around 120 resources at once resulted in it failing to add the fx_version and game 'gta5' to the fxmanifest.lua. Though it did change the name and correctly copy the contents. I don't see much of a pattern, it happen in random scripts such as seatshuffle, esx_holsterweapon, and some others. I can re-do the conversion and check which scripts it failed to do again if needed.

**Comment by Holfz** [comment]
weird, I have doing for a large server (like 200+ resources) and not getting something like this,It did the name change means it can find a file path properly. Did __resource.lua of that resources has something like `resource_manifest_version` ?

**Comment by Holfz** [comment]
That is my fault, The fxv2 `NEED` to specify a game which __resource didn't. So this script find `resource_manifest_version` and replace with `"fx_version 'adamant'\ngame " + game_type;` which is not work

This will be fix soon

**Comment by Holfz** [comment]
Please try to re-do the conversion with version 1.2 again

**Comment by ivoryyy** [comment]
Will post what i posted on the forums here as well. 
Tried again. This time all had the FX_version and Game ‘gta5’ but now some were missing the client and server scripts and there was one was missing the client_script before the ‘client.lua’.

Some scripts that were missing server or client:
Hospitalheal
Postalcodes
JF_Seatshuffle
Breathalyzer (The one that was released with the standalone inventory)
fax-hidecmds
and some others

Edit: I tried a second time to see if it is randomly failing on scripts or if it is specific scripts. Those same scripts that were missing it before are still missing it. So i assume its something specific with these. I am going to try with only these few scripts and see what happens.

**Comment by Holfz** [comment]
🤦‍♂ Also, Some script has the client of server on top first.

**Comment by Holfz** [comment]
Try an v1.3 again, Sorry for bothering you.

**Comment by ivoryyy** [comment]
That fixed all of them except the breathalyzer script. Here is the one im using. 
https://forum.cfx.re/t/release-basic-breathalyzer-and-inventory-script/74622

**Comment by Holfz** [comment]
Please try an v1.4.

And again, Sorry for bothering you.

--------------------------------

FYI, There is a manifest style that used for testing. [link](https://github.com/Holfz/noah_fxmanifest_converter/tree/master/testing_resources)

**Comment by ivoryyy** [comment]
Just went through all 120 fxmanifests from that conversion. Didnt see any issues. Looks good.

**Comment by Holfz** [comment]
Nice! Please close an issue if solved and no more issue !

**Comment by ivoryyy** [comment]
Closing now, thank you for your work!
