### ISSUE TITLE
Optimize.

### ISSUE THREAD

**Issue by benzon** [Holfz/noah_fxmanifest_converter#2]
Only copy folder structure and the __resource.lua files, insted of copying everything, would be faster and make more sence.

**Comment by benzon** [comment]
Easy fix would be.

`filter		: /^((?!__resource)[\s\S])*$/`

This way you only get the __resource.lua files copyed over and avoid it having to copy everything, what could take ages for some servers.

Besides that they then just copy the files inside converted in to there resource folder, search for __resource.lua and remove thos files.

**Comment by Holfz** [comment]
It's can be enchancement, But in some case. Copy entire resource can make like a 2nd backup for avoid data lost. Isn't it ?

**Comment by benzon** [comment]
it dos somehow, but if you do it like a sane person you copy your files anyways to have a backup :D
